- name: copy folder xml file to location
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml

- name: Create a folder {{item}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item}}"
    password: "{{jenkins_password}}"
    url: http://172.31.36.116:8080
    user: admin
  loop: "{{folders}}"

- name: create multi branch pipeline jobs
  ansible.builtin.include_tasks: "mbranch-mbranch-pipeline.yml"
  loop: "{{ci_pipeline_jobs}}"

- name: create Single branch pipeline jobs
  ansible.builtin.include_tasks: "sbranch-mbranch-pipeline.yml"
  loop: "{{sbranch_pipeline_jobs}}"

