- name: check if job exists or not - {{item.dir}}/{{item.name}}
  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://172.31.36.116:8080 -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes

- name: create {{item.dir}}/{{item.name}}-config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)
  when: out.rc == 3

- name: Create {{item.dir}}/{{item.name}}-jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.36.116:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.rc == 3



