- name: copy xml file to location
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create a {{item.name}} job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    password: "{{jenkins_password}}"
    url: http://172.31.36.116:8080
    user: admin